[build]
  base ="/"
  command = "npm install --force && CI=false npm run build"
  publish = "build/"

[[redirects]]
  from = "/code/*"
  to = "/code/:splat"
  status = 200

[[redirects]]
  from = "/text/*"
  to = "/text/:splat"
  status = 200

[[redirects]]
  from = "/help/*"
  to = "/help/:splat"
  status = 200
